=== bsarasuspe/SZA_3PraktikaOrok/xml/liburua.dtd
<!ELEMENT liburuak (liburua)*>
<!ATTLIST liburuak azkenid IDREF #REQUIRED>
<!ELEMENT liburua (titulua, egilea, hizkuntza, kategoria, data, sinopsia, irudia, deskarga)>
<!ATTLIST liburua id ID #REQUIRED>
<!ELEMENT titulua (#PCDATA)>
<!ELEMENT egilea (#PCDATA)>
<!ELEMENT hizkuntza (#PCDATA)>
<!ELEMENT kategoria (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT sinopsia (#PCDATA)>
<!ELEMENT irudia (#PCDATA)>
<!ELEMENT deskarga (#PCDATA)>

=== bsarasuspe/SZA_3PraktikaOrok/xml/liburuak.xml
<?xml version="1.0"?>
<!DOCTYPE liburuak SYSTEM "liburua.dtd">
<liburuak azkenid="21">
    <liburua id="1">
        <titulua>Harry Potter y la piedra filosofal</titulua>
        <egilea>J.K. Rowling</egilea>
        <hizkuntza>Gaztelera</hizkuntza>
        <kategoria>Fantasia</kategoria>
        <data>1997-06-26</data>
        <sinopsia>Harry Potter se ha quedado hu&#xE9;rfano y vive en casa de sus abominables t&#xED;os y el insoportable primo Dudley. Harry se siente muy triste y solo, hasta que un buen d&#xED;a recibe una carta que cambiar&#xE1; su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el Colegio Hogwarts de Magia.</sinopsia>
        <irudia>https://i.kinja-img.com/gawker-media/image/upload/s--AUsfSKba--/c_scale,f_auto,fl_progressive,q_80,w_800/18eqlwy2pur67jpg.jpg</irudia>
        <deskarga>https://www.amazon.es/Viajo-sola-SELLER-Samuel-Bjork/dp/8490629161</deskarga>
    </liburua>
<liburua id="2"><titulua>Viajo Sola</titulua><egilea>Samuel Bjork</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Suspensea</kategoria><data>2015-10-08</data><sinopsia>Un hombre sale a pasear con su perro para recuperarse de la resaca y de su cargo de conciencia. De repente el perro sale corriendo entre los &#xE1;rboles. All&#xED; el hombre descubre a una ni&#xF1;a que cuelga de un &#xE1;rbol, balance&#xE1;ndose sobre el suelo. Con una mochila escolar en la espalda y un cartel alrededor del cuello que dice &#xAB;Viajo sola&#xBB;.</sinopsia><irudia>https://static.megustaleer.com.mx/images/libros_650_x/ESL57218.jpg</irudia><deskarga>https://www.amazon.es/Viajo-sola-SELLER-Samuel-Bjork/dp/8490629161</deskarga></liburua><liburua id="12"><titulua>El misterio del tren azul</titulua><egilea>Agatha Christie</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Suspensea</kategoria><data>1928-03-29</data><sinopsia>Cuando el lujoso Tren Azul llega a Niza, un guardia intenta despertar a Ruth Kettering para anunciarle su parada. Pero ella no despertar&#xE1; nunca m&#xE1;s, ya que un disparo de gran calibre la ha matado, desfigurando sus rasgos hasta volverla casi irreconocible.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/51oYncA9XFL.jpg</irudia><deskarga>https://drive.google.com/file/d/14axRqhheS9tBWZzepcS5WVO62mGgQqWf/view</deskarga></liburua><liburua id="13"><titulua>La casa de Bernarda Alba</titulua><egilea>Federico Garc&#xED;a Lorca</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Komedia</kategoria><data>1945-03-08</data><sinopsia>Tras la muerte de su segundo esposo, Bernarda Alba se recluye e impone un luto riguroso y asfixiante por ocho a&#xF1;os, prohibiendo a sus cinco hijas a que vayan a la fiesta. Cuando Angustias, la primog&#xE9;nita y la &#xFA;nica hija del primer marido, hereda una fortuna, atrae a un pretendiente, Pepe el Romano.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/615f6q1i3TL.jpg</irudia><deskarga>https://biblioteca.org.ar/libros/157286.pdf</deskarga></liburua><liburua id="14"><titulua>Cr&#xF3;nica de una muerte anunciada</titulua><egilea>Gabriel Garc&#xED;a M&#xE1;rquez</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Suspensea</kategoria><data>1981-01-21</data><sinopsia>En un peque&#xF1;o y aislado pueblo en la costa del Caribe, se casan Bayardo San Rom&#xE1;n, un hombre rico y reci&#xE9;n llegado, y &#xC1;ngela Vicario. ... A&#xF1;os despu&#xE9;s, &#xC1;ngela Vicario estar&#xED;a escribiendo cada d&#xED;a a Bayardo, primero formalmente, despu&#xE9;s con cartas de joven enamorada y, al final, fingiendo enfermedades.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/91Dax7AnPpL.jpg</irudia><deskarga>http://www.juansanmartin.net/biblioteca/gabriel/cronicadeunamuerte.pdf</deskarga></liburua><liburua id="15"><titulua>El c&#xF3;digo Da Vinci</titulua><egilea>Dan Brown</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Suspensea</kategoria><data>2003-02-21</data><sinopsia>La mayor conspiraci&#xF3;n de los &#xFA;ltimos 2000 a&#xF1;os est&#xE1; a punto de ser desvelada. Robert Langdon recibe una llamada en mitad de la noche: el conservador del museo del Louvre ha sido asesinado en extra&#xF1;as circunstancias y junto a su cad&#xE1;ver ha aparecido un desconcertante mensaje cifrado.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/51WmNPpn5sL.jpg</irudia><deskarga>https://uves.cl/wp-content/uploads/2020/03/5671_Planetadelibros-KeepReadingEnCasa-El-Codigo-Da-Vinci.pdf</deskarga></liburua><liburua id="16"><titulua>Zaborretan azkenak</titulua><egilea>Itxaro Borda</egilea><hizkuntza>Euskara</hizkuntza><kategoria>Suspensea</kategoria><data>2019-05-02</data><sinopsia>Zaborretan azkenak izenburuak ere zentzu-geruza zenbait iradokitzen ditu, hiru ardatz hauetan gurutzatzen direnak: hondakinen kudeaketa eta ekologismoa; zabor-bilketa eta gizarte-eredua; zabor-imajinarioak jendetasunarekin uztartzen dituzten diskurtsoak. Hiru geruza horietan katramilaturik dabilkigu Amaia Ezpeldoiren gogoa Zaborretan azkenak nobelako orriotan.</sinopsia><irudia>https://booktegi.eus/-cover.php?book=141</irudia><deskarga>https://drive.google.com/file/d/1Tcs8etfAaTSH1eCmIZYyCT1n7inI6CEv/view?usp=sharing</deskarga></liburua><liburua id="17"><titulua>Tom Sawyer, detektibe</titulua><egilea>Mark Twain</egilea><hizkuntza>Euskara</hizkuntza><kategoria>Komedia</kategoria><data>1896-08-25</data><sinopsia>Tom Sawyer, detektibea lan ezin hobea duen polizia klasikoa da. Conan Doyleren lanak eraginda, Tom lehen ordenako detektibe gisa ageri da bertan, bere Huk Finn leialak lagunduta, Watson doktorearen papera gogotsu antzeztuko duena.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/71DWhebthLL.jpg</irudia><deskarga>https://drive.google.com/file/d/14lDtZYS1zHVeX8FpyEqfpfXQoen_x7Rh/view?usp=sharing</deskarga></liburua><liburua id="18"><titulua>Heptamerona</titulua><egilea>Margarita Nafarroakoa</egilea><hizkuntza>Euskara</hizkuntza><kategoria>Komedia</kategoria><data>2021-06-14</data><sinopsia>Margarita Nafarroakoak 1559an idatzi zuen Heptamerona. Frantsesez idatzi zuen, eta gaur arte ez da bere osotasunean euskarara itzuli. Guztira 72 ipuin edo istoriok osatzen dute liburua, eta zortzi liburuki edo &#x2018;egunetan&#x2019; antolatuta daude. Hainbat ipuinen ikuspuntu aurrerakoiak ere &#x2013;besteak beste, genero-ikuspegitik&#x2013; gaur egungo irakurleentzako erakargarri bihurtzen du Nafarroako erreginaren liburua. Datozen urteotan Booktegik &#x2013;Nafar Ateneoarekin elkarlanean&#x2013; ipuin guztiak eskainiko ditu euskaraz, liburu klasikoa horrela berreskuratuz, eta gurera ekarriz. Oraingo honetan, Heptameronaren lehenengo eguna &#x2013;hamar ipuin guztira&#x2013; argitaratu dugu.</sinopsia><irudia>https://booktegi.eus/-cover.php?book=260</irudia><deskarga>https://drive.google.com/file/d/1Tcs8etfAaTSH1eCmIZYyCT1n7inI6CEv/view?usp=sharing</deskarga></liburua><liburua id="19"><titulua>Murder on the Orient Express</titulua><egilea>Agatha Christie</egilea><hizkuntza>Ingelesa</hizkuntza><kategoria>Suspensea</kategoria><data>1934-01-01</data><sinopsia>When a murder occurs on the train on which he's travelling, celebrated detective Hercule Poirot is recruited to solve the case. Hercule Poirot, the best detective in the world, decides to travel on the Orient Express. The train accidentally gets stopped because of a small avalanche.</sinopsia><irudia>https://images-na.ssl-images-amazon.com/images/I/91WNTrjWeTL.jpg</irudia><deskarga>http://detective.gumer.info/anto/christie_8_2.pdf</deskarga></liburua><liburua id="20"><titulua>The Great Gatsby</titulua><egilea>F. Scott Fitzgerald</egilea><hizkuntza>Ingelesa</hizkuntza><kategoria>Komedia</kategoria><data>1970-01-01</data><sinopsia>The Great Gatsby, third novel by F. Scott Fitzgerald, published in 1925 by Charles Scribner's Sons. Set in Jazz Age New York, the novel tells the tragic story of Jay Gatsby, a self-made millionaire, and his pursuit of Daisy Buchanan, a wealthy young woman whom he loved in his youth.</sinopsia><irudia>https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg</irudia><deskarga>https://www.wsfcs.k12.nc.us/cms/lib/NC01001395/Centricity/Domain/7935/Gatsby_PDF_FullText.pdf</deskarga></liburua><liburua id="21"><titulua>Harry Potter y la c&#xE1;mara secreta</titulua><egilea>J. K. Rowling</egilea><hizkuntza>Gaztelera</hizkuntza><kategoria>Fantasia</kategoria><data>2002-11-29</data><sinopsia>Tras derrotar una vez m&#xE1;s a lord Voldemort, su siniestro enemigo en Harry Potter y la piedra filosofal, Harry espera impaciente en casa de sus insoportables t&#xED;os el inicio del segundo curso del Colegio Hogwarts de Magia. Sin embargo, la espera dura poco, pues un elfo aparece en su habitaci&#xF3;n y le advierte que una amenaza mortal se cierne sobre la escuela. As&#xED; pues, Harry no se lo piensa dos veces y, acompa&#xF1;ado de Ron, su mejor amigo, se dirige a Hogwarts en un coche volador. Pero &#xBF;puede un aprendiz de mago defender la escuela de los malvados que pretenden destruirla? Sin saber que alguien hab&#xED;a abierto la C&#xE1;mara de los Secretos, dejando escapar una serie de monstruos peligrosos, Harry y sus amigos Ron y Hermione tendr&#xE1;n que enfrentarse con ara&#xF1;as gigantes, serpientes encantadas, fantasmas enfurecidos y, sobre todo, con la mism&#xED;sima reencarnaci&#xF3;n de su m&#xE1;s temible adversario.</sinopsia><irudia>https://resumiendolo.com/wp-content/uploads/2018/02/Harry-Potter-y-la-c%C3%A1mara-secreta-4-e1518549159273.jpg</irudia><deskarga>http://www.jfk.edu.ec/jfk/images/librospdf/J.K._Rowling_-_2Harry_Potter_y_la_Camara_secreta.pdf</deskarga></liburua></liburuak>
